# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: API Testing Rest Assured

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 00 18 * * *
    - cron: 00 03 * * *

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Execute test
      run: mvn clean test

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
          name: TestNG result
          path: target/surefire-reports/junitreports/TEST-*.xml
          reporter: java-junit

    - name: Generate test summary
      id: summary
      run: |
          PASSED=$(grep -oP '(?<=Tests run: )[0-9]+' target/surefire-reports/*.txt | awk '{sum+=$1} END {print sum}')
          FAILED=$(grep -oP '(?<=Failures: )[0-9]+' target/surefire-reports/*.txt | awk '{sum+=$1} END {print sum}')
          SKIPPED=$(grep -oP '(?<=Skipped: )[0-9]+' target/surefire-reports/*.txt | awk '{sum+=$1} END {print sum}')
          echo "PASSED=$PASSED" >> $GITHUB_ENV
          echo "FAILED=$FAILED" >> $GITHUB_ENV
          echo "SKIPPED=$SKIPPED" >> $GITHUB_ENV

    - name: Send results to Slack
      run: |
          if [ "$FAILED" -gt 0 ]; then
            COLOR="#FF0000"  # Red if failed
          else
            COLOR="#36A64F"  # Green if all passed
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"attachments\": [
              {
                \"color\": \"$COLOR\",
                \"blocks\": [
                  {
                    \"type\": \"header\",
                    \"text\": {\"type\": \"plain_text\", \"text\": \"📊 API Test Execution Report\", \"emoji\": true}
                  },
                  {
                    \"type\": \"divider\"
                  },
                  {
                    \"type\": \"section\",
                    \"fields\": [
                      {\"type\": \"mrkdwn\", \"text\": \"*✅ Passed:* $PASSED\"},
                      {\"type\": \"mrkdwn\", \"text\": \"*❌ Failed:* $FAILED\"},
                      {\"type\": \"mrkdwn\", \"text\": \"*⚠️ Skipped:* $SKIPPED\"}
                    ]
                  }
                ]
              }
            ]
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
