# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: API Testing Rest Assured

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 00 18 * * *
    - cron: 00 03 * * *

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Execute test
      run: mvn clean test

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
          name: TestNG result
          path: target/surefire-reports/junitreports/TEST-*.xml
          reporter: java-junot

    - name: Send results to Slack
      if: always()
      run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \"*API Test Summary:*\n✅ Passed: $PASSED\n❌ Failed: $FAILED\n⚠️ Skipped: $SKIPPED\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
